name: vatom_wallet
description: Vatom Wallet SDK for flutter.
homepage: https://vatom.com
version: 0.0.39
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vatom_wallet_sdk: 
    path: "../../wallet/apps/flutter-embed-sdk"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
