name: vatom_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  location: ^6.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.1
  webview_flutter_wkwebview: ^3.13.0
  # vatom_wallet_sdk: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
